= DubGeiser

include::urls.adoc[]

== {url-vimconfig}[vimconfig]
[.lead]
My Neovim configuration.

I've been using Vim as my main editor for quite a while; Going through the SQL dump of a an ancient blog of mine, I ran into a statement for inserting data in the `blog_post`, title: "Going Vim", date: "2004-11-25 12:05".

After running `vimtutor`, I fairly quickly switched to the GUI version of Vim (GVim, I was on Windows at the time); I found the font rendering to be better, it had nicer color schemes and the default copypaste actions just worked out-of-the-box.

When I switched to MacOS, I ran MacVim up until the end of 2020.  And then I switched to {url-neovim}[Neovim] almost overnight and haven't regretted it yet.  Even if I don't have the normal copypaste action like I would like it... yet.
I cleaned and tweaked my config accordingly, removing settings that Neovim has set by default.  So do be aware that this configuration has only ever really been run on Mac Neovim.

== {url-tilde}[tilde]
[.lead]
My dotfiles.

I rely on Bash and the usual command line tools and started putting my preferences in git around 2013. I switch to a 1 shell + tmux flow every now and again, but I used to always go back to MacVim + iTerm2, up until end 2020, when I fully switched to Neovim.

== {url-mbinstall}[mbinstall]
[.lead]
Basically a Bash script for installing my MacBook.

NOTE: Since I'm getting a bit more familiar with {url-ansible}[Ansible], this will probably be replaced by some playbooks.

== {url-knife}[knife]
[.lead]
PHP Code collection, geared towards developing with {url-fork}[Fork CMS].

NOTE: Knife isn't maintained anymore, the repo is archived.

== {url-rpi}[Raspberry PI]
[.lead]
Using small computers as home servers and media players.

I bought a 4B in 2019, installed Samba, Apache, Transmission daemon, amongst other things, and it runs in the home network as a basic server.  Another RPI (an older B+ model) has Kodi installed via {url-libreelec}[LibreELEC] and is quite capable of 1080p playback without hick-ups.  If we ever buy a new television, I'll replace it with a model that can handle 4K of course, but for now, this works quite well.
